# Generated by Django 5.2.1 on 2025-07-14 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_avatar_alter_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('is_accepted', models.BooleanField(default=None, null=True, verbose_name='принято')),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_invites', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_invites', to=settings.AUTH_USER_MODEL, verbose_name='кого')),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('from_client', 'to_client'), name='unique_friend_invite')],
            },
        ),
    ]
